DELETE http://localhost:3003/api/products/11
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJrb2NrbyIsImlhdCI6MTY3ODQ4NDU5OH0.x5bnBEogm0A9Hgd6WG953UNrSlodB_2_f5dQWR87D30
