POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "seco",
  "name": "Šećo",
  "password": "lozinka",
  "email": "seco@example.com",
  "address": "Seco street 1, City, Somelandia"
}