env:
  PORT: ${{secrets.PORT}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SECRET: ${{secrets.SECRET}}

name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm run install-packages
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build:ui
      - name: Jest tests
        run: cd e-commerce-frontend/ && npm run test
      - name: e2e testing
        uses: cypress-io/github-action@v5
        with:
          start: npm run start
          wait-on: "http://localhost:3003"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') && !contains(join(toJson(github.event.commits.*.message), ' '), '#minor') }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.RAGS_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Bump minor version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') && contains(join(toJson(github.event.commits.*.message), ' '), '#minor') }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.RAGS_TOKEN }}
          DEFAULT_BUMP: minor
