name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm run install-packages
      - name: Build
        run: npm run build:ui
      - name: e2e testing
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:test
          wait-on: http://localhost:3003
